server:
  port: 7077
spring:
  application:
    name: hystrix
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.25.128:7070/eureka/

ribbon:
  eureka:
    enabled: true
