#spring.application.name=zuul
#server.port=7073
#
## routes to serviceId
##zuul.routes.api-a.path=/api-a/**
##zuul.routes.api-a.serviceId=service-A
#
#zuul.routes.api-b.path=/api-b/**
#zuul.routes.api-b.serviceId=ribbon
#
##zuul.routes.api-b.path=/service-b/**
##zuul.routes.api-b.serviceId=service-b
#
## routes to url
#zuul.routes.api-a-url.path=/api-a-url/**
#zuul.routes.api-a-url.url=http://localhost:7074/
#
#eureka.client.serviceUrl.defaultZone=http://localhost:7070/eureka/


spring:
  application:
    name: zuul

server:
  port: 7073


zuul:
  host:
    max-per-route-connections: 1000
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: ribbon
    service-B:
      path: /service-B/**
      serviceId: service-B
    hystrix:
      path: /hystrix/**
      serviceId: hystrix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka/