
spring:
  application:
    name: zuul

server:
  port: 7073


zuul:
  host:
    max-per-route-connections: 1000
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: ribbon
    hystrix:
      path: /hystrix/**
      serviceId: hystrix

eureka:
  client:
    service-url:
      defaultZone: http://192.168.25.128:7070/eureka/